### ISSUE TITLE
Can't access users list to direct message

### ISSUE THREAD

**Issue by bsdtux** [hikalium/slack-tui#1]
Using slack-tui 0.1.2-2 on manjaro and having problems accessing the Users list for direct messaging. I am not sure if this is by design or if I am missing something.

**Comment by A-Manning** [comment]
I have the same issue on Ubuntu 16.04

**Comment by hikalium** [comment]
Thank you for reporting this issue.
This behavior was as expected because it was not implemented (sorry for the confusion).
But now, direct messages is supported on v0.2.0 so please `npm update -g slack-tui` then you'll find it works!

**Comment by bsdtux** [comment]
Thank you. just upgraded and it works perfectly. many thanks for this application.
